name: First Workflow
on: 
  workflow_dispatch:
  pull_request:
    types: [opended, edited]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print 1
        run: echo "Hello world"
      - name: Print 2
        run: |
          echo "1"
          echo "2"
          echo "3"
          
